Repository CodeEditApp/CodeEditSourceEditor, pull requests merged in 2022-10, with the labels that each got.

#71 Improved Line Number Appearance
  Sources/CodeEditTextView/STTextViewController.swift
Labels: enhancement, UI

#74 [Feat]: Add language support for `Haskell`
  Package.swift
  Sources/CodeEditTextView/CodeLanguage/CodeLanguage.swift
  Sources/CodeEditTextView/CodeLanguage/TreeSitterLanguage.swift
  Sources/CodeEditTextView/CodeLanguage/TreeSitterModel.swift
  Sources/CodeEditTextView/Documentation.docc/CodeLanguage.md
  Sources/CodeEditTextView/Documentation.docc/TreeSitterModel.md
  Tests/CodeEditTextViewTests/CodeEditTextViewTests.swift
Labels: enhancement, editor

#73 [Feat]: Add language support for `Elixir` / Update docs for `Zig`
  Package.swift
  Sources/CodeEditTextView/CodeLanguage/CodeLanguage.swift
  Sources/CodeEditTextView/CodeLanguage/TreeSitterLanguage.swift
  Sources/CodeEditTextView/CodeLanguage/TreeSitterModel.swift
  Sources/CodeEditTextView/Documentation.docc/Add-Languages.md
  Sources/CodeEditTextView/Documentation.docc/CodeLanguage.md
  Sources/CodeEditTextView/Documentation.docc/TreeSitterModel.md
  Tests/CodeEditTextViewTests/CodeEditTextViewTests.swift
Labels: documentation, enhancement, editor

#86 [chore]: Refactor to use binary framework for `tree-sitter` language grammars
  .github/workflows/build-documentation.yml
  .github/workflows/tests.yml
  Package.resolved
  Package.swift
  Sources/CodeEditTextView/CodeEditTextView.swift
  Sources/CodeEditTextView/CodeLanguage/CodeLanguage.swift
  Sources/CodeEditTextView/CodeLanguage/TreeSitterLanguage.swift
  Sources/CodeEditTextView/CodeLanguage/TreeSitterModel.swift
  Sources/CodeEditTextView/Documentation.docc/Add-Languages.md
  Sources/CodeEditTextView/Documentation.docc/CodeLanguage.md
  Sources/CodeEditTextView/Documentation.docc/Documentation.md
  Sources/CodeEditTextView/Documentation.docc/TreeSitterModel.md
  Sources/CodeEditTextView/Highlighting/Highlighter.swift
  Sources/CodeEditTextView/STTextViewController.swift
  Sources/CodeEditTextView/TreeSitter/TreeSitterClient.swift
  Tests/CodeEditTextViewTests/CodeEditTextViewTests.swift
Labels: enhancement, PRIORITY
